### PR TITLE
Add a script to return the system version

### PR DESCRIPTION
**Pull request by pietrocaselani**
This is a request by @jfvicente It's a script that connects on Agile API to get the system configuration variables and search for the config "app.release.name".
Special thanks to @frlwolf

### CODE REVIEW

**Comment by pietrocaselani** [comment]
@fernandovsv I think that `@agile version <system>` will be better than `@botname agile version <system>`. I talked to Binho, he think this will cause trouble, the whole idea is to simplify everyone's life. However, Bibi is the boss ... So, I, unhapply, will do. :disappointed:

**Comment by pietrocaselani** [comment]
PR updated! I kept the olds commands for compatibility, but remove the documentation... I dont want to "re educate" all teams to new commands. 
I didn't do any new command, and have no idea how to do the `agile help` or `agile list` in an easy way.
I hope that satisfies @gabrielinvolves !

**Comment by fernandovsv** [comment]
With hubot-help, we can search for help by just doing this:

hubot>> hubot help <query> - Displays all help commands that match <query>.

With that said, ur PR already solves the issue, good job ;)

**Comment by gabrielinvolves** [comment]
@pietrocaselani LOL i`ve just read it now!

I just exposed an idea in the issue #26 and it was open to discuss.. I just want to organize all the work because in few years we are going to have a lot of commands..  In the next time we can discuss in the issue rather than cry alone.

**Pull request merged**
